apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - name: mysql-port
          containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value:
        - name: MYSQL_USER
          value:
        - name: MYSQL_PASSWORD
          value:
        - name: MYSQL_DATABASE
          value:
